# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/yanmaobaimo"

[social.params]
icon = "brand-github"

[[social]]
identifier = "bilibili"
name = "哔哩哔哩"
url = "https://space.bilibili.com/105274179"

[social.params]
icon = "brand-bilibili"

[[social]]
identifier = "抖音"
name = "抖音"
url = "https://v.douyin.com/iUg4s3x2"

[social.params]
icon = "brand-tiktok"

[[social]]
identifier = "网易云音乐"
name = "网易云音乐"
url = "https://music.163.com/#/playlist?id=5264890008"

[social.params]
icon = "brand-netease-music"

[[social]]
identifier = "mail"
name = "https://yanmaobaimo@gmail.com"
url = "yanmaobaimo@gmail.com"

[social.params]
icon = "mail"