name: Deploy Hugo site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # 拉取源码
      - name: Checkout source
        uses: actions/checkout@v4

      # 设置 Hugo
      - name: Install Hugo Extended
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.139.4"
          extended: true

      # 生成静态文件
      - name: Build
        run: hugo --minify

      # 部署到 gh-pages 分支
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
